import type { CmaPackages } from "$lib/types/environments";

/**
 * Input shape for the Dockerfile generator. Mirrors the {slug, baseEnvSlug,
 * packages, name} subset of an EnvironmentDetail — pure inputs, no DB or I/O.
 */
export type DockerfileInputs = {
	slug: string;
	name: string;
	baseEnvSlug: string | null;
	packages: CmaPackages;
};

/**
 * Image URL of the root sandbox image every custom environment ultimately
 * extends. Envs either FROM this directly (baseEnvSlug is null) or FROM
 * another env's latest imageTag (single-level inheritance).
 */
export const ROOT_SANDBOX_IMAGE =
	"gitea-ryzen.tail286401.ts.net/giteaadmin/openshell-sandbox:latest";

/** Where generated Dockerfiles live in the workflow-builder repo. */
export const DOCKERFILE_DIR = "services/openshell-sandbox/environments";

export function dockerfilePathForSlug(slug: string): string {
	return `${DOCKERFILE_DIR}/Dockerfile.${slug}`;
}

/**
 * Resolve the concrete `FROM` reference for a given env. When the env
 * inherits from another, we need that parent env's imageTag (the SHA-pinned
 * tag, not its slug). 1-level inheritance — no recursion.
 */
export type BaseImageResolver = (slug: string) => string | null | undefined;

/**
 * Generate a Dockerfile for the given environment. Pure function — no I/O.
 * Output is committed to stacks/workflow-builder where Tekton picks it up.
 *
 * Layer order matches CMA's documented install order: apt → cargo → gem → go
 * → npm → pip. Same order produces the same cache hits on rebuilds.
 *
 * BuildKit cache mounts are used so incremental rebuilds complete in seconds
 * rather than re-downloading the whole set.
 */
export function generateDockerfile(
	env: DockerfileInputs,
	opts: { baseImageResolver?: BaseImageResolver; timestamp?: string } = {},
): string {
	const ts = opts.timestamp ?? new Date().toISOString();
	const baseImage = resolveBaseImage(env.baseEnvSlug, opts.baseImageResolver);

	const lines: string[] = [];
	lines.push(
		`# syntax=docker/dockerfile:1.7`,
		``,
		`# Auto-generated sandbox environment: ${env.slug}`,
		`# Name: ${env.name}`,
		`# Generated: ${ts}`,
		`# Edit via workflow-builder admin console /workspaces/<slug>/environments/${env.slug} —`,
		`# DO NOT edit this file by hand. Regeneration overwrites it on env save.`,
		``,
		`ARG BASE_IMAGE=${baseImage}`,
		`FROM \${BASE_IMAGE}`,
		``,
		`# System package layers run as root; drop back to the sandbox user at the end`,
		`# so the image matches OpenShell's runtime expectations.`,
		`USER root`,
		``,
	);

	const { apt, cargo, gem, go, npm, pip } = env.packages ?? {};

	if (apt && apt.length > 0) {
		lines.push(
			`# apt layer`,
			`RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \\`,
			`    --mount=type=cache,target=/var/lib/apt,sharing=locked \\`,
			`    DEBIAN_FRONTEND=noninteractive apt-get update -qq \\`,
			` && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \\`,
			`    ${apt.map(shellQuote).join(" ")} \\`,
			` && rm -rf /var/lib/apt/lists/*`,
			``,
		);
	}

	if (cargo && cargo.length > 0) {
		lines.push(
			`# cargo layer — installs via rustup's cargo which is expected in the base image`,
			`RUN --mount=type=cache,target=/usr/local/cargo/registry,sharing=locked \\`,
			`    /usr/local/bin/cargo install ${cargo.map(shellQuote).join(" ")}`,
			``,
		);
	}

	if (gem && gem.length > 0) {
		lines.push(
			`# gem layer — Ruby packages`,
			`RUN /usr/local/bin/gem install ${gem.map(shellQuote).join(" ")}`,
			``,
		);
	}

	if (go && go.length > 0) {
		lines.push(
			`# go layer — installs via "go install"`,
			`RUN --mount=type=cache,target=/root/go/pkg,sharing=locked \\`,
			`    /usr/local/go/bin/go install ${go.map(shellQuote).join(" ")}`,
			``,
		);
	}

	if (npm && npm.length > 0) {
		lines.push(
			`# npm layer — installed globally so /usr/bin CLIs are available at runtime`,
			`RUN --mount=type=cache,target=/root/.npm,sharing=locked \\`,
			`    npm install --global ${npm.map(shellQuote).join(" ")}`,
			``,
		);
	}

	if (pip && pip.length > 0) {
		// /sandbox/.venv is created in the root base image by uv. We install
		// into it directly so declared packages are importable from the venv
		// python the agent uses (PATH starts with /sandbox/.venv/bin).
		lines.push(
			`# pip layer — packages into the sandbox venv under /sandbox/.venv`,
			`RUN --mount=type=cache,target=/root/.cache/pip,sharing=locked \\`,
			`    /sandbox/.venv/bin/pip install --no-compile --disable-pip-version-check \\`,
			`    ${pip.map(shellQuote).join(" ")}`,
			``,
		);
	}

	lines.push(
		`# Drop back to the sandbox user so OpenShell's policy (run_as_user: sandbox)`,
		`# matches what the image actually runs as. The sandbox user is defined in the`,
		`# root openshell-sandbox image.`,
		`USER sandbox`,
		`WORKDIR /sandbox`,
		``,
	);

	return lines.join("\n");
}

function resolveBaseImage(
	baseSlug: string | null,
	resolver?: BaseImageResolver,
): string {
	if (!baseSlug) return ROOT_SANDBOX_IMAGE;
	if (resolver) {
		const resolved = resolver(baseSlug);
		if (resolved) return resolved;
	}
	// Fallback — if we can't resolve the parent's imageTag (e.g. it hasn't
	// been built yet), point at the `:latest` tag of the parent profile's
	// registry slot. The Tekton pipeline will still succeed against whatever
	// the most-recent build produced.
	return `gitea-ryzen.tail286401.ts.net/giteaadmin/openshell-sandbox-${baseSlug}:latest`;
}

/**
 * Shell-quote a package spec so it can be safely appended to a RUN line.
 * Package specs are already validated by the registry to match a restricted
 * regex (alphanumerics + . _ @ / + = < > ~ -), so this is belt-and-suspenders
 * — the output just wraps anything containing shell metacharacters.
 */
function shellQuote(spec: string): string {
	if (/^[a-zA-Z0-9._+@/-]+$/.test(spec)) return spec;
	return `'${spec.replace(/'/g, `'\\''`)}'`;
}

/**
 * Small helper for the admin UI preview + the build endpoint to see what the
 * image tag will be. Tag includes `:dev` as a placeholder before the first
 * build; once Tekton stamps a git SHA the tag becomes `:git-<sha>`.
 */
export function expectedImageTagForSlug(slug: string): string {
	return `gitea-ryzen.tail286401.ts.net/giteaadmin/openshell-sandbox-${slug}:latest`;
}

/**
 * Narrow helper — returns true when the env has at least one installable
 * entry. Used to short-circuit rebuilds when an env is saved with the same
 * manifest and only metadata changed.
 */
export function hasAnyPackages(packages: CmaPackages | undefined): boolean {
	return Object.values(packages ?? {}).some((v) => Array.isArray(v) && v.length > 0);
}
