import { describe, expect, it } from "vitest";
import { repairWorkflowDefinitionShape } from "./sdk";

describe("repairWorkflowDefinitionShape", () => {
	it("repairs common generated workflow shape mistakes", () => {
		const malformed = {
			document: {
				dsl: "1.0.0",
				name: "resolve-issue",
				title: "Resolve Issue",
				description: "Generated by AI",
			},
			do: [
				{
					plan: {
						call: "daprSwePlan",
						for: {
							in: "${ [1,2] }",
							do: [
								{
									review: {
										call: "daprSweReview",
									},
								},
							],
						},
					},
				},
				{
					notify: {
						emit: {
							event: {
								name: "workflow.completed",
								source: "event",
								data: {
									success: true,
								},
							},
						},
					},
				},
				{
					branch: {
						switch: [
							{
								yes: {
									when: "${ .needsChanges }",
									then: "develop",
								},
								no: {
									then: "end",
								},
							},
						],
					},
				},
			],
		};

		const repaired = repairWorkflowDefinitionShape(malformed);
		const workflow = repaired.workflow as Record<string, unknown>;
		const document = workflow.document as Record<string, unknown>;
		const tasks = workflow.do as Array<Record<string, unknown>>;
		const planTask = tasks[0]?.plan as Record<string, unknown>;
		const emitTask = tasks[1]?.notify as Record<string, unknown>;

		expect(document.summary).toBe("Generated by AI");
		expect(document.description).toBeUndefined();
		expect(planTask.do).toEqual([
			{
				review: {
					call: "daprSweReview",
				},
			},
		]);
		expect((planTask.for as Record<string, unknown>).do).toBeUndefined();
		expect(emitTask.emit).toEqual({
			event: {
				with: {
					name: "workflow.completed",
					data: {
						success: true,
					},
					source: "https://workflow-builder.local/events/event",
				},
			},
		});
		expect(repaired.actions.length).toBeGreaterThanOrEqual(2);
	});
});
