"""Action handlers that wrap dapr-swe agent runners for workflow-builder orchestration.

Each handler takes (input_data, node_outputs) and returns
{"success": bool, "data": dict, "error": str | None}.
"""

from __future__ import annotations

import asyncio
import logging
import os
from typing import Any

import httpx

from src.events import publish_event, register_execution, update_execution_status, post_agent_event, post_issue_comment
from src.integrations.github_app import get_github_app_installation_token
from src.sandbox.openshell import OpenShellBackend, create_openshell_sandbox
from src.tracing import trace_activity

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _resolve(input_data: dict, node_outputs: dict, key: str, node_label: str = "") -> Any:
    """Resolve a value from input_data or a previous node's output.

    Searches: input_data → node_outputs[*].data → node_outputs[*].data.data (nested).
    The orchestrator stores node results as: {data: {success, data: {actual_fields}}}.
    """
    if key in input_data:
        return input_data[key]
    # Search all previous node outputs
    for nid, out in node_outputs.items():
        if not isinstance(out, dict):
            continue
        # Direct in output
        if key in out:
            return out[key]
        # In output.data
        data = out.get("data", {})
        if isinstance(data, dict):
            if key in data:
                return data[key]
            # In output.data.data (nested function-router response)
            inner = data.get("data", {})
            if isinstance(inner, dict) and key in inner:
                return inner[key]
    return None


def _reconnect_sandbox(sandbox_id: str) -> OpenShellBackend:
    """Reconnect to an existing sandbox by its ID."""
    return create_openshell_sandbox(sandbox_id=sandbox_id)


def _build_pr_body(plan: dict, issue_number: int) -> str:
    """Build a PR description from the plan."""
    summary = plan.get("summary", "Automated implementation")
    steps = plan.get("steps", [])

    parts = [
        "## Summary",
        "",
        summary,
        "",
        f"Closes #{issue_number}",
        "",
    ]

    if steps:
        parts.append("## Changes")
        parts.append("")
        for step in steps:
            parts.append(f"- **{step.get('title', '')}**: {step.get('description', '')}")
        parts.append("")

    parts.append("---")
    parts.append("*Generated by dapr-swe*")

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# 1. Initialize -- create sandbox, clone repo, read AGENTS.md
# ---------------------------------------------------------------------------


def handle_initialize(input_data: dict, node_outputs: dict) -> dict:
    """Create sandbox, clone the repo, and read AGENTS.md.

    Expects owner and repo in input_data (or from a trigger node output).
    Returns sandbox_id, working_dir, agents_md, github_token.
    """
    owner = _resolve(input_data, node_outputs, "owner")
    repo = _resolve(input_data, node_outputs, "repo")

    if not owner or not repo:
        return {"success": False, "data": {}, "error": "Missing required fields: owner, repo"}

    # Get GitHub token — prefer connection token from workflow-builder, fall back to App token
    token = (
        _resolve(input_data, node_outputs, "githubToken")
        or _resolve(input_data, node_outputs, "github_token")
        or _resolve(input_data, node_outputs, "repositoryToken")
        or os.environ.get("GITHUB_TOKEN")
    )
    if not token:
        import concurrent.futures
        with concurrent.futures.ThreadPoolExecutor() as pool:
            token = pool.submit(
                lambda: asyncio.run(get_github_app_installation_token())
            ).result(timeout=30)

    if not token:
        return {"success": False, "data": {}, "error": "No GitHub token available"}

    # Derive deterministic sandbox ID from context
    issue_num = _resolve(input_data, node_outputs, "issue_number") or "latest"
    sandbox_id = f"dapr-swe-{owner}-{repo}-{issue_num}"

    # Create sandbox (reconnects if sandbox_id already exists)
    try:
        sandbox = create_openshell_sandbox(sandbox_id=sandbox_id)
    except Exception as exc:
        return {"success": False, "data": {}, "error": f"Failed to create sandbox: {exc}"}

    sandbox_id = sandbox.id
    working_dir = f"/sandbox/{repo}"

    # Clone repository (skip if already cloned — idempotent for activity replay)
    check = sandbox.execute(f"test -d {working_dir}/.git && echo exists", timeout=10)
    if "exists" in (check.output or ""):
        logger.info("Repo already cloned at %s, skipping clone", working_dir)
    else:
        clone_url = f"https://x-access-token:{token}@github.com/{owner}/{repo}.git"
        clone_depth = _resolve(input_data, node_outputs, "cloneDepth") or "50"
        result = sandbox.execute(
            f"git clone --depth={clone_depth} {clone_url} {working_dir}",
            timeout=120,
        )
        if result.exit_code != 0:
            return {
                "success": False,
                "data": {"sandbox_id": sandbox_id},
                "error": f"CLONE FAIL: {result.output[:200]}",
            }

    # Store credentials for later push
    sandbox.execute(
        f"echo 'https://x-access-token:{token}@github.com' > /tmp/.git-credentials",
        timeout=10,
    )

    # Configure git identity
    sandbox.execute(
        f"cd {working_dir} && "
        "git config user.email 'dapr-swe[bot]@users.noreply.github.com' && "
        "git config user.name 'dapr-swe[bot]'",
        timeout=10,
    )

    # Read AGENTS.md if present
    agents_md = ""
    agents_result = sandbox.execute(f"cat {working_dir}/AGENTS.md 2>/dev/null", timeout=10)
    if agents_result.exit_code == 0 and agents_result.output.strip():
        agents_md = agents_result.output.strip()

    # Publish workflow started event (best-effort, non-blocking).
    # NOTE: Do NOT call register_execution() here — this handler is called
    # by the orchestrator via function-router. The BFF webhook already created
    # the execution record. Calling register_execution() would hit the BFF's
    # /api/internal/agent/workflows/execute which starts a NEW orchestrator
    # workflow, creating an infinite cascade loop.
    issue_ref = f"{owner}/{repo}#{input_data.get('issue_number', '')}"
    publish_event("dapr-swe.workflow.started", {"issue": issue_ref, "title": input_data.get("title", ""), "sandbox_id": sandbox_id})

    return {
        "success": True,
        "data": {
            "sandbox_id": sandbox_id,
            "working_dir": working_dir,
            "agents_md": agents_md,
            "github_token": token,
            "wb_execution_id": "",
        },
        "error": None,
    }


# ---------------------------------------------------------------------------
# 2. Plan -- run PlannerAgent
# ---------------------------------------------------------------------------


def handle_plan(input_data: dict, node_outputs: dict) -> dict:
    """Run the PlannerAgent to produce an implementation plan.

    Expects sandbox_id and issue context (issue_number, title, body, etc.).
    """
    from src.agents.planner import run_planner

    sandbox_id = _resolve(input_data, node_outputs, "sandbox_id")
    if not sandbox_id:
        return {"success": False, "data": {}, "error": "Missing required field: sandbox_id"}

    sandbox = _reconnect_sandbox(sandbox_id)

    # Build issue context from all available fields
    issue_context = {}
    for key in ("owner", "repo", "issue_number", "title", "body", "comments",
                "sender", "working_dir", "agents_md", "github_token"):
        val = _resolve(input_data, node_outputs, key)
        if val is not None:
            issue_context[key] = val

    # Resolve optional configuration overrides from workflow-builder UI
    model = _resolve(input_data, node_outputs, "model")
    max_iters = _resolve(input_data, node_outputs, "maxIterations")
    prompt_extra = _resolve(input_data, node_outputs, "systemPromptOverride")

    try:
        plan = run_planner(
            sandbox, issue_context,
            model_override=model,
            max_iterations=int(max_iters) if max_iters else None,
            system_prompt_extra=prompt_extra,
        )
    except Exception as exc:
        logger.exception("PlannerAgent failed")
        return {"success": False, "data": {}, "error": f"PlannerAgent failed: {exc}"}

    # Publish plan-created events
    wb_exec_id = _resolve(input_data, node_outputs, "wb_execution_id") or ""
    issue_ref = f"{_resolve(input_data, node_outputs, 'owner')}/{_resolve(input_data, node_outputs, 'repo')}#{_resolve(input_data, node_outputs, 'issue_number')}"
    publish_event("dapr-swe.plan.created", {"issue": issue_ref, "summary": plan.get("summary", ""), "steps": len(plan.get("steps", []))})
    update_execution_status(wb_exec_id, "planning", 25)
    post_agent_event(wb_exec_id, "plan_created", {"phase": "planning", "summary": plan.get("summary", ""), "stepCount": len(plan.get("steps", []))})

    return {
        "success": True,
        "data": {
            "plan": plan,
            "summary": plan.get("summary", ""),
            "step_count": len(plan.get("steps", [])),
        },
        "error": None,
    }


# ---------------------------------------------------------------------------
# 3. Develop -- run DeveloperAgent for a single step
# ---------------------------------------------------------------------------


def handle_develop(input_data: dict, node_outputs: dict) -> dict:
    """Run the DeveloperAgent for a single plan step.

    Expects sandbox_id, step (dict), and issue/plan context.
    """
    from src.agents.developer import run_developer

    sandbox_id = _resolve(input_data, node_outputs, "sandbox_id")
    if not sandbox_id:
        return {"success": False, "data": {}, "error": "Missing required field: sandbox_id"}

    sandbox = _reconnect_sandbox(sandbox_id)

    # Build issue context from all available sources
    issue_context = {}
    for key in ("owner", "repo", "issue_number", "title", "body", "comments",
                "sender", "working_dir", "agents_md", "github_token"):
        val = _resolve(input_data, node_outputs, key)
        if val is not None:
            issue_context[key] = val

    plan = _resolve(input_data, node_outputs, "plan") or {}

    # Resolve event tracking context
    wb_exec_id = _resolve(input_data, node_outputs, "wb_execution_id") or ""
    issue_ref = f"{_resolve(input_data, node_outputs, 'owner')}/{_resolve(input_data, node_outputs, 'repo')}#{_resolve(input_data, node_outputs, 'issue_number')}"

    # Resolve optional configuration overrides from workflow-builder UI
    model = _resolve(input_data, node_outputs, "model")
    max_iters = _resolve(input_data, node_outputs, "maxIterations")
    prompt_extra = _resolve(input_data, node_outputs, "systemPromptOverride")
    dev_overrides = dict(
        model_override=model,
        max_iterations=int(max_iters) if max_iters else None,
        system_prompt_extra=prompt_extra,
    )

    # Get step(s) to implement
    step = _resolve(input_data, node_outputs, "step")
    steps = plan.get("steps", [])

    # If no specific step, implement all steps from the plan
    if not step and steps:
        results = []
        for i, s in enumerate(steps):
            logger.info("Implementing step %d/%d: %s", i + 1, len(steps), s.get("title", ""))
            publish_event("dapr-swe.step.started", {"issue": issue_ref, "step_index": i, "step_title": s.get("title", "")})
            try:
                r = run_developer(sandbox=sandbox, step=s, issue_context=issue_context, plan=plan, **dev_overrides)
                results.append(r)
                publish_event("dapr-swe.step.completed", {"issue": issue_ref, "step_index": i, "step_title": s.get("title", ""), "status": r.get("status", "")})
                update_execution_status(wb_exec_id, "implementing", 40 + i * 10)
                post_agent_event(wb_exec_id, "step_completed", {"phase": "implementing", "stepIndex": i, "stepTitle": s.get("title", "")})
            except Exception as exc:
                logger.warning("Step %d failed: %s", i + 1, exc)
                results.append({"status": "error", "error": str(exc)})
        return {
            "success": True,
            "data": {"status": "completed", "steps_completed": len(results), "results": results},
        }

    if not step:
        # No step and no plan steps — implement based on issue description
        step = {
            "title": "Implement changes",
            "description": issue_context.get("body", issue_context.get("title", "")),
            "files": [],
        }

    publish_event("dapr-swe.step.started", {"issue": issue_ref, "step_index": 0, "step_title": step.get("title", "")})
    try:
        result = run_developer(
            sandbox=sandbox,
            step=step,
            issue_context=issue_context,
            plan=plan,
            **dev_overrides,
        )
    except Exception as exc:
        logger.exception("DeveloperAgent failed")
        return {"success": False, "data": {}, "error": f"DeveloperAgent failed: {exc}"}

    publish_event("dapr-swe.step.completed", {"issue": issue_ref, "step_index": 0, "step_title": step.get("title", ""), "status": result.get("status", "")})
    update_execution_status(wb_exec_id, "implementing", 50)
    post_agent_event(wb_exec_id, "step_completed", {"phase": "implementing", "stepIndex": 0, "stepTitle": step.get("title", "")})

    return {
        "success": True,
        "data": {
            "status": result.get("status", "unknown"),
            "files_changed": result.get("files_changed", []),
        },
        "error": None,
    }


# ---------------------------------------------------------------------------
# 4. Review -- run ReviewerAgent on the full diff
# ---------------------------------------------------------------------------


def handle_review(input_data: dict, node_outputs: dict) -> dict:
    """Run the ReviewerAgent on the current diff.

    Expects sandbox_id, working_dir, and issue/plan context.
    """
    from src.agents.reviewer import run_reviewer

    sandbox_id = _resolve(input_data, node_outputs, "sandbox_id")
    working_dir = _resolve(input_data, node_outputs, "working_dir")

    if not sandbox_id:
        return {"success": False, "data": {}, "error": "Missing required field: sandbox_id"}
    if not working_dir:
        return {"success": False, "data": {}, "error": "Missing required field: working_dir"}

    sandbox = _reconnect_sandbox(sandbox_id)

    # Get the full diff
    diff_result = sandbox.execute(f"cd {working_dir} && git diff HEAD", timeout=60)
    diff = diff_result.output or ""

    # If no unstaged changes, check for staged changes or commits ahead of origin
    if not diff.strip():
        diff_result = sandbox.execute(
            f"cd {working_dir} && git diff origin/main...HEAD",
            timeout=60,
        )
        diff = diff_result.output or ""

    if not diff.strip():
        return {
            "success": True,
            "data": {"approved": True, "feedback": "No changes to review", "suggestions": []},
            "error": None,
        }

    # Build issue context and plan
    issue_context = {}
    for key in ("owner", "repo", "issue_number", "title", "body"):
        val = _resolve(input_data, node_outputs, key)
        if val is not None:
            issue_context[key] = val

    plan = _resolve(input_data, node_outputs, "plan") or {}

    # Resolve optional configuration overrides from workflow-builder UI
    model = _resolve(input_data, node_outputs, "model")

    try:
        review = run_reviewer(diff=diff, issue_context=issue_context, plan=plan, model_override=model)
    except Exception as exc:
        logger.exception("ReviewerAgent failed")
        return {"success": False, "data": {}, "error": f"ReviewerAgent failed: {exc}"}

    # Publish review events
    wb_exec_id = _resolve(input_data, node_outputs, "wb_execution_id") or ""
    issue_ref = f"{_resolve(input_data, node_outputs, 'owner')}/{_resolve(input_data, node_outputs, 'repo')}#{_resolve(input_data, node_outputs, 'issue_number')}"
    update_execution_status(wb_exec_id, "reviewing", 75)
    publish_event("dapr-swe.review.completed", {"issue": issue_ref, "approved": review.get("approved", False)})

    return {
        "success": True,
        "data": {
            "approved": review.get("approved", False),
            "feedback": review.get("feedback", ""),
            "suggestions": review.get("suggestions", []),
        },
        "error": None,
    }


# ---------------------------------------------------------------------------
# 5. Commit & PR -- stage, commit, push, and open a GitHub PR
# ---------------------------------------------------------------------------


def handle_commit_pr(input_data: dict, node_outputs: dict) -> dict:
    """Stage changes, create branch, commit, push, and open a GitHub PR.

    Expects sandbox_id, working_dir, owner, repo, issue_number, github_token.
    """
    sandbox_id = _resolve(input_data, node_outputs, "sandbox_id")
    working_dir = _resolve(input_data, node_outputs, "working_dir")
    owner = _resolve(input_data, node_outputs, "owner")
    repo = _resolve(input_data, node_outputs, "repo")
    issue_number = _resolve(input_data, node_outputs, "issue_number")
    token = _resolve(input_data, node_outputs, "github_token")
    title = _resolve(input_data, node_outputs, "title") or "Untitled issue"
    plan = _resolve(input_data, node_outputs, "plan") or {}

    for field, val in [("sandbox_id", sandbox_id), ("working_dir", working_dir),
                       ("owner", owner), ("repo", repo),
                       ("issue_number", issue_number), ("github_token", token)]:
        if not val:
            return {"success": False, "data": {}, "error": f"Missing required field: {field}"}

    # Resolve optional configuration overrides from workflow-builder UI
    draft = _resolve(input_data, node_outputs, "draft")
    base_branch = _resolve(input_data, node_outputs, "baseBranch") or "main"
    pr_title = _resolve(input_data, node_outputs, "prTitle") or f"fix: {title} [closes #{issue_number}]"

    # draft is True unless explicitly set to "false"
    is_draft = True if draft is None else str(draft).lower() != "false"

    sandbox = _reconnect_sandbox(sandbox_id)
    import time; branch_name = f"dapr-swe/issue-{issue_number}-{int(time.time())}"

    # Check for actual changes
    status_result = sandbox.execute(f"cd {working_dir} && git status --porcelain", timeout=10)
    if not status_result.output.strip():
        return {
            "success": True,
            "data": {"pr_url": "", "branch": branch_name, "status": "no_changes"},
            "error": None,
        }

    # Configure git user, create branch, stage, commit
    commit_result = sandbox.execute(
        f"cd {working_dir} && "
        "git config user.email 'dapr-swe[bot]@users.noreply.github.com' && "
        "git config user.name 'dapr-swe[bot]' && "
        f"git checkout -b {branch_name} && "
        "git add -A && "
        f'git commit -m "{pr_title}"',
        timeout=60,
    )
    if commit_result.exit_code != 0:
        return {
            "success": False,
            "data": {"branch": branch_name},
            "error": f"Failed to commit: {commit_result.output}",
        }

    # Push
    push_result = sandbox.execute(
        f"cd {working_dir} && git push -u origin {branch_name}",
        timeout=120,
    )
    if push_result.exit_code != 0:
        return {
            "success": False,
            "data": {"branch": branch_name},
            "error": f"Push failed: {push_result.output}",
        }

    # Open PR via GitHub API
    pr_body = _build_pr_body(plan, int(issue_number))
    pr_data = {
        "title": pr_title,
        "head": branch_name,
        "base": base_branch,
        "body": pr_body,
        "draft": is_draft,
    }

    try:
        with httpx.Client(timeout=30) as client:
            resp = client.post(
                f"https://api.github.com/repos/{owner}/{repo}/pulls",
                headers={
                    "Authorization": f"Bearer {token}",
                    "Accept": "application/vnd.github+json",
                    "X-GitHub-Api-Version": "2022-11-28",
                },
                json=pr_data,
            )
    except Exception as exc:
        return {
            "success": False,
            "data": {"branch": branch_name},
            "error": f"GitHub API request failed: {exc}",
        }

    if resp.status_code == 201:
        pr_url = resp.json().get("html_url", "")
        publish_event("dapr-swe.pr.created", {"issue": f"{owner}/{repo}#{issue_number}", "pr_url": pr_url})
        # Post issue comment (notification)
        post_issue_comment(owner, repo, issue_number, f"I've opened a draft PR: {pr_url}", token)
        publish_event("dapr-swe.workflow.completed", {"issue": f"{owner}/{repo}#{issue_number}", "status": "success", "pr_url": pr_url})
        return {
            "success": True,
            "data": {"pr_url": pr_url, "branch": branch_name, "status": "success"},
            "error": None,
        }
    elif resp.status_code == 422:
        return {
            "success": True,
            "data": {"pr_url": "", "branch": branch_name, "status": "already_exists"},
            "error": None,
        }
    else:
        return {
            "success": False,
            "data": {"branch": branch_name},
            "error": f"PR creation failed ({resp.status_code}): {resp.text}",
        }


# ---------------------------------------------------------------------------
# 6. Solve -- single DurableAgent that does everything end-to-end
# ---------------------------------------------------------------------------


def handle_solve(input_data: dict, node_outputs: dict) -> dict:
    """Run the full CodingAgent: explore → plan → implement → test → commit → PR.

    Expects sandbox_id, working_dir, owner, repo, issue_number, github_token
    from the initialize step's output (via node_outputs).
    """
    sandbox_id = _resolve(input_data, node_outputs, "sandbox_id")
    working_dir = _resolve(input_data, node_outputs, "working_dir")
    owner = _resolve(input_data, node_outputs, "owner")
    repo = _resolve(input_data, node_outputs, "repo")
    issue_number = _resolve(input_data, node_outputs, "issue_number")
    token = _resolve(input_data, node_outputs, "github_token")
    agents_md = _resolve(input_data, node_outputs, "agents_md") or ""
    title = _resolve(input_data, node_outputs, "title") or "Untitled issue"
    body = _resolve(input_data, node_outputs, "body") or ""
    comments = _resolve(input_data, node_outputs, "comments") or []

    for field, val in [("sandbox_id", sandbox_id), ("working_dir", working_dir),
                       ("owner", owner), ("repo", repo)]:
        if not val:
            return {"success": False, "data": {}, "error": f"Missing required field: {field}"}

    # Resolve model from config (workflow-builder UI passes this)
    model = _resolve(input_data, node_outputs, "model") or os.environ.get("LLM_MODEL_ID", "claude-opus-4-6")
    max_iterations = int(_resolve(input_data, node_outputs, "maxIterations") or 1000)

    # Reconnect to existing sandbox
    sandbox = _reconnect_sandbox(sandbox_id)

    # Build issue context
    issue_context = {
        "owner": owner,
        "repo": repo,
        "issue_number": issue_number,
        "title": title,
        "body": body,
        "comments": comments,
        "github_token": token,
        "working_dir": working_dir,
        "agents_md": agents_md,
    }

    try:
        from dapr_agents import DurableAgent
        from dapr_agents.agents.configs import AgentExecutionConfig, WorkflowRetryPolicy
        from dapr_agents.workflow.runners import AgentRunner
        from src.llm_providers import resolve_llm_client
        from src.prompts.coding_agent import construct_system_prompt
        from src.tools.sandbox import make_sandbox_tools
        from src.tools.github import make_github_tools
        from src.tools.web import make_web_tools
        from src.tools.linear import make_linear_tools
        from src.tools.slack import make_slack_tools

        # Build all tools bound to this sandbox + context
        all_tools = (
            make_sandbox_tools(sandbox)
            + make_github_tools(sandbox, issue_context)
            + make_web_tools()
            + make_linear_tools(issue_context)
            + make_slack_tools(issue_context)
        )

        # Get the shared workflow runtime from main.py
        from src.main import _workflow_runtime

        # Create DurableAgent with shared runtime
        agent = DurableAgent(
            name="CodingAgent",
            role="Senior Software Engineer",
            goal="Resolve the assigned issue by implementing changes and opening a PR",
            system_prompt=construct_system_prompt(working_dir, issue_context),
            llm=resolve_llm_client(model),
            tools=all_tools,
            execution=AgentExecutionConfig(
                max_iterations=max_iterations,
            ),
            retry_policy=WorkflowRetryPolicy(
                max_attempts=3,
                initial_backoff_seconds=10,
                max_backoff_seconds=60,
                backoff_multiplier=2.0,
            ),
            runtime=_workflow_runtime,
        )

        # Pre-start agent (registers workflows on runtime). Catch if already registered
        # from a previous call — the shared runtime persists across requests.
        try:
            agent.start()
        except (ValueError, RuntimeError) as start_err:
            logger.debug("Agent start (likely already registered): %s", start_err)

        # Run via AgentRunner (async — use asyncio.run in the thread)
        async def _run_agent():
            runner = AgentRunner(name="solve-runner", timeout_in_seconds=1800)
            try:
                result = await runner.run(agent, payload={"task": _format_solve_task(issue_context)}, wait=True)
                return result
            finally:
                runner.shutdown(agent)

        result = asyncio.run(_run_agent())

        return {
            "success": True,
            "data": {"result": str(result) if result else "Agent completed"},
            "error": None,
        }

    except Exception as exc:
        logger.exception("CodingAgent failed")
        return {"success": False, "data": {}, "error": f"CodingAgent failed: {exc}"}


def _format_solve_task(issue_context: dict) -> str:
    """Format the issue into the initial task prompt for the CodingAgent."""
    parts = [f"## Issue: {issue_context.get('title', 'Untitled')}"]
    parts.append("")
    parts.append(issue_context.get("body", "No description provided."))
    comments = issue_context.get("comments", [])
    if comments:
        parts.append("\n## Comments")
        for c in comments:
            user = c.get("user", "unknown")
            parts.append(f"<untrusted-content user=\"{user}\">")
            parts.append(c.get("body", ""))
            parts.append("</untrusted-content>")
    parts.append(f"\nRepository: {issue_context.get('owner', '')}/{issue_context.get('repo', '')}")
    parts.append(f"Issue: #{issue_context.get('issue_number', '')}")
    parts.append(f"Working directory: {issue_context.get('working_dir', '/sandbox')}")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Action handler registry
# ---------------------------------------------------------------------------

ACTION_HANDLERS: dict[str, Any] = {
    "dapr-swe/initialize": handle_initialize,
    "dapr-swe/solve": handle_solve,
    # Legacy handlers route to solve for backwards compat
    "dapr-swe/plan": handle_plan,
    "dapr-swe/develop": handle_develop,
    "dapr-swe/review": handle_review,
    "dapr-swe/commit-pr": handle_commit_pr,
}
