CREATE TABLE "code_functions" (
  "id" text PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "description" text NULL,
  "version" text NOT NULL DEFAULT '0.1.0',
  "language" text NOT NULL,
  "entrypoint" text NOT NULL DEFAULT 'main',
  "path" text NULL,
  "source" text NOT NULL,
  "source_hash" text NOT NULL,
  "semantic_model" jsonb NULL,
  "input_schema" jsonb NULL,
  "return_type" jsonb NULL,
  "imports" jsonb NULL,
  "diagnostics" jsonb NULL,
  "capabilities" jsonb NULL,
  "is_enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  "created_by" text NULL,
  CONSTRAINT "code_functions_slug_unique" UNIQUE ("slug"),
  CONSTRAINT "code_functions_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
