/**
 * Activepieces action-catalog source backed by the piece_metadata DB table.
 *
 * piece_metadata rows are generated by the piece-runtime image's
 * `sync-metadata` step (services/piece-mcp-server/src/metadata-catalog.ts
 * `buildPieceCatalogRow` is the authoritative shape) and validated at
 * piece-runtime startup against the same digest. This module is the PRIMARY
 * source of AP actions for the canvas catalog — it replaced the live fetch of
 * the retired fn-activepieces service.
 *
 * ActionId format is preserved from the fn-activepieces catalog so saved
 * workflows keep resolving:
 *   id/name        `<pieceName>-<actionName>`   (e.g. "gmail-send_email")
 *   slug/call      `<pieceName>/<actionName>`   (the function-router slug)
 */

import { and, desc, eq } from 'drizzle-orm';
import { db } from '$lib/server/db';
import { pieceMetadata } from '$lib/server/db/schema';
import type {
	ActionAuthMetadata,
	ActionCatalogDetail,
	ActionCatalogServiceSnapshot,
	ActionFieldMetadata,
} from './types';

/** serviceId stamped on DB-sourced AP catalog entries. */
export const AP_CATALOG_SERVICE_ID = 'activepieces';

/** Must match piece-mcp-server's CATALOG_SCHEMA_VERSION. */
const PIECE_CATALOG_SCHEMA_VERSION = 1;

const CACHE_TTL_MS = 30_000;

type UnknownRecord = Record<string, unknown>;

type PieceCatalogSource = {
	actions: ActionCatalogDetail[];
	service: ActionCatalogServiceSnapshot;
};

let cachedSource: { expiresAt: number; value: PieceCatalogSource } | null = null;

/** AP property type → JSON Schema type (display fallback when the stored inputSchema lacks the prop). */
const PROP_SCHEMA_TYPE: Record<string, string> = {
	SHORT_TEXT: 'string',
	LONG_TEXT: 'string',
	NUMBER: 'number',
	CHECKBOX: 'boolean',
	DROPDOWN: 'string',
	STATIC_DROPDOWN: 'string',
	MULTI_SELECT_DROPDOWN: 'array',
	STATIC_MULTI_SELECT_DROPDOWN: 'array',
	DATE_TIME: 'string',
	FILE: 'object',
	OBJECT: 'object',
	JSON: 'object',
	ARRAY: 'array',
	DYNAMIC: 'object',
	MARKDOWN: 'string',
};

const AUTH_PROP_TYPES = new Set([
	'OAUTH2',
	'SECRET_TEXT',
	'BASIC_AUTH',
	'CUSTOM_AUTH',
	'NO_AUTH',
]);

/** Prop types whose options resolver is a runtime function (dynamic dropdowns). */
const DYNAMIC_OPTION_PROP_TYPES = new Set(['DROPDOWN', 'MULTI_SELECT_DROPDOWN']);

function isRecord(value: unknown): value is UnknownRecord {
	return !!value && typeof value === 'object' && !Array.isArray(value);
}

function stringOr(value: unknown, fallback = ''): string {
	return typeof value === 'string' ? value : fallback;
}

function stringArray(value: unknown): string[] {
	return Array.isArray(value)
		? value.filter((item): item is string => typeof item === 'string' && item.trim().length > 0)
		: [];
}

function humanizeLabel(value: string): string {
	return value
		.split(/[-_\s]+/)
		.filter(Boolean)
		.map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
		.join(' ');
}

function classifyAuthKind(auth: UnknownRecord): string {
	const type = stringOr(auth.type).toUpperCase();
	switch (type) {
		case 'OAUTH2':
			return 'oauth2';
		case 'SECRET_TEXT':
			return 'secret-text';
		case 'BASIC_AUTH':
			return 'basic-auth';
		case 'CUSTOM_AUTH':
			return 'custom-auth';
		default:
			break;
	}
	if ('authUrl' in auth || 'tokenUrl' in auth || 'scope' in auth || 'grantType' in auth) {
		return 'oauth2';
	}
	if ('username' in auth && 'password' in auth) {
		return 'basic-auth';
	}
	if ('props' in auth) {
		return 'custom-auth';
	}
	return 'unknown';
}

function buildAuthMetadata(
	pieceAuth: unknown,
	required: boolean,
): ActionAuthMetadata | null {
	if (!pieceAuth) return null;
	const entries = Array.isArray(pieceAuth) ? pieceAuth : [pieceAuth];
	const records = entries.filter(isRecord);
	if (records.length === 0) return null;

	const first = records[0];
	const authType = stringOr(first.type).trim();
	return {
		required,
		displayName: stringOr(first.displayName).trim() || null,
		description: stringOr(first.description).trim() || null,
		kinds: records.map(classifyAuthKind),
		authType: authType || null,
		connectionResourceType: authType ? authType.toLowerCase() : null,
	};
}

function normalizeStaticOptions(options: unknown): Array<{ label: string; value: unknown }> {
	if (Array.isArray(options)) {
		return options.flatMap((item) => {
			if (isRecord(item)) {
				const label =
					stringOr(item.label) ||
					stringOr(item.displayName) ||
					stringOr(item.name) ||
					stringOr(item.title) ||
					stringOr(item.value) ||
					stringOr(item.id);
				const value = item.value ?? item.id ?? item.key ?? item.name ?? item.label;
				return label && value !== undefined ? [{ label, value }] : [];
			}
			if (typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean') {
				return [{ label: String(item), value: item }];
			}
			return [];
		});
	}
	if (isRecord(options)) {
		return normalizeStaticOptions(options.options);
	}
	return [];
}

function buildActionFields(
	props: unknown,
	dynamicProps: unknown,
	inputSchemaProperties: UnknownRecord,
): ActionFieldMetadata[] | null {
	if (!isRecord(props)) return null;
	const dynamic = isRecord(dynamicProps) ? dynamicProps : {};

	const fields: ActionFieldMetadata[] = [];
	for (const [name, rawProp] of Object.entries(props)) {
		if (!isRecord(rawProp)) continue;
		const propertyType = stringOr(rawProp.type);
		if (AUTH_PROP_TYPES.has(propertyType)) continue;

		// Dynamic-dropdown wiring: rows synced after the dynamicProps extension
		// carry refreshers/refreshOnSearch; older rows fall back to detecting
		// dynamic-ness from the prop type (props JSONB drops the options fn).
		const dynamicMeta = isRecord(dynamic[name]) ? (dynamic[name] as UnknownRecord) : null;
		const isDynamic = dynamicMeta !== null || DYNAMIC_OPTION_PROP_TYPES.has(propertyType);
		const refreshers = stringArray(dynamicMeta?.refreshers);
		const refreshOnSearch = dynamicMeta?.refreshOnSearch === true;
		const staticValues = isDynamic ? [] : normalizeStaticOptions(rawProp.options);

		const schemaProp = isRecord(inputSchemaProperties[name])
			? (inputSchemaProperties[name] as UnknownRecord)
			: null;

		fields.push({
			name,
			displayName: stringOr(rawProp.displayName).trim() || humanizeLabel(name),
			description: stringOr(rawProp.description).trim() || null,
			propertyType: propertyType || 'string',
			schemaType:
				stringOr(schemaProp?.type) || PROP_SCHEMA_TYPE[propertyType] || 'string',
			required: rawProp.required === true,
			defaultValue: rawProp.defaultValue ?? null,
			dependsOn: refreshers,
			refreshers,
			refreshOnSearch,
			options: isDynamic
				? { kind: 'dynamic', refreshers, refreshOnSearch }
				: staticValues.length > 0
					? { kind: 'static', values: staticValues }
					: null,
		});
	}
	return fields;
}

function buildActionDetail(input: {
	pieceName: string;
	actionName: string;
	action: UnknownRecord;
	row: {
		displayName: string;
		logoUrl: string;
		description: string | null;
		version: string;
		auth: unknown;
		categories: string[];
		catalogDigest: string | null;
		catalogSourceImage: string | null;
		availableOnly: boolean;
	};
}): ActionCatalogDetail {
	const { pieceName, actionName, action, row } = input;
	// Available-only pieces are AP-catalog metadata for pieces NOT bundled in the
	// image — discoverable, but with no runnable code (no ap-<piece>-service). They
	// must NOT be insertable on the canvas or appear runtime-ready, else a user
	// could add an action that can never execute. docs/activepieces-catalog-expansion.md.
	const availableOnly = row.availableOnly === true;
	const fnName = `${pieceName}-${actionName}`;
	const call = `${pieceName}/${actionName}`;
	const displayName = stringOr(action.displayName) || actionName;
	const description = stringOr(action.description);

	const inputSchema = isRecord(action.inputSchema)
		? (action.inputSchema as UnknownRecord)
		: null;
	const inputSchemaProperties = isRecord(inputSchema?.properties)
		? (inputSchema.properties as UnknownRecord)
		: {};
	const hasSchemaProperties = Object.keys(inputSchemaProperties).length > 0;

	const requireAuth = action.requireAuth === true && row.auth != null;
	const auth = buildAuthMetadata(row.auth, requireAuth);
	const fields = buildActionFields(
		action.props,
		action.dynamicProps,
		inputSchemaProperties,
	);

	const taskConfig: UnknownRecord = {
		call,
		with: {
			body: {
				input: {},
				metadata: {
					pieceName,
					actionName,
					sourceKind: 'integration',
				},
			},
		},
		...(inputSchema && hasSchemaProperties
			? {
					input: {
						schema: {
							format: 'json',
							document: inputSchema,
						},
					},
				}
			: {}),
	};

	return {
		id: fnName,
		slug: call,
		name: fnName,
		displayName,
		description,
		providerId: pieceName,
		providerLabel: row.displayName || humanizeLabel(pieceName),
		providerIconUrl: row.logoUrl || null,
		category: row.categories[0] || null,
		serviceId: AP_CATALOG_SERVICE_ID,
		kind: 'catalog-function',
		visibility: 'public-callable',
		compatibility: 'compatible',
		group: pieceName,
		version: row.version || '1.0.0',
		language: 'typescript',
		entrypoint: actionName,
		sourceKind: 'integration',
		insertable: !availableOnly,
		auth,
		fields,
		tags: ['activepieces'],
		doc: description || null,
		inputSchema,
		outputSchema: null,
		semanticModel: null,
		sourceCode: null,
		sourceHtml: null,
		sw: {
			functionName: fnName,
			definition: taskConfig,
			taskConfig,
			warnings: [],
		},
		runtime: {
			registered: !availableOnly,
			ready: !availableOnly,
			lastSeenAt: new Date().toISOString(),
			errors: [],
			features: availableOnly
				? ['piece-metadata-db', 'available-only']
				: ['piece-metadata-db', 'per-piece-knative'],
		},
		rendered: null,
		raw: {
			pieceName,
			actionName,
			requireAuth,
			availableOnly,
			pieceDescription: row.description,
			actionDigest: stringOr(action.digest) || null,
			catalogDigest: row.catalogDigest,
			catalogSourceImage: row.catalogSourceImage,
		},
	};
}

/**
 * Load AP catalog actions from piece_metadata (latest synced row per piece,
 * canonical catalog schema only). Throwing is fine — loadRemoteActionCache
 * surfaces failures as partialErrors.
 */
export async function loadPieceMetadataActionSource(): Promise<PieceCatalogSource> {
	if (cachedSource && cachedSource.expiresAt > Date.now()) {
		return cachedSource.value;
	}
	if (!db) {
		throw new Error('database is not configured');
	}

	const rows = await db
		.selectDistinctOn([pieceMetadata.name], {
			name: pieceMetadata.name,
			displayName: pieceMetadata.displayName,
			logoUrl: pieceMetadata.logoUrl,
			description: pieceMetadata.description,
			version: pieceMetadata.version,
			auth: pieceMetadata.auth,
			actions: pieceMetadata.actions,
			categories: pieceMetadata.categories,
			catalogDigest: pieceMetadata.catalogDigest,
			catalogSourceImage: pieceMetadata.catalogSourceImage,
			catalogSyncedAt: pieceMetadata.catalogSyncedAt,
			availableOnly: pieceMetadata.availableOnly,
		})
		.from(pieceMetadata)
		// Exclude available-only rows: their pieces have no runnable code (no
		// ap-<piece>-service), so their actions must NOT appear in the canvas action
		// catalog (they'd render as un-insertable clutter). Discovery of available-only
		// pieces lives in the connections surface (mcp-availability), not here.
		.where(
			and(
				eq(pieceMetadata.catalogSchemaVersion, PIECE_CATALOG_SCHEMA_VERSION),
				eq(pieceMetadata.availableOnly, false)
			)
		)
		.orderBy(pieceMetadata.name, desc(pieceMetadata.catalogSyncedAt));

	const actions: ActionCatalogDetail[] = [];
	for (const row of rows) {
		if (!isRecord(row.actions)) continue;
		for (const [actionName, action] of Object.entries(row.actions)) {
			if (!isRecord(action)) continue;
			actions.push(
				buildActionDetail({
					pieceName: row.name,
					actionName,
					action,
					row: {
						displayName: row.displayName,
						logoUrl: row.logoUrl,
						description: row.description,
						version: row.version,
						auth: row.auth,
						categories: row.categories ?? [],
						catalogDigest: row.catalogDigest,
						catalogSourceImage: row.catalogSourceImage,
						availableOnly: row.availableOnly === true,
					},
				}),
			);
		}
	}

	const value: PieceCatalogSource = {
		actions,
		service: {
			service: AP_CATALOG_SERVICE_ID,
			version: `piece-metadata-v${PIECE_CATALOG_SCHEMA_VERSION}`,
			runtime: 'piece-runtime',
			ready: true,
			features: ['piece-metadata-db', 'per-piece-knative'],
			registeredWorkflows: [],
			registeredActivities: [],
			additional: {
				pieces: rows.length,
				actions: actions.length,
			},
		},
	};

	cachedSource = { expiresAt: Date.now() + CACHE_TTL_MS, value };
	return value;
}

export type PieceCatalogFunctionSummary = {
	name: string;
	version: string;
	displayName: string;
	description: string;
	pieceName: string;
	actionName: string;
	providerId: string;
	providerLabel: string;
	providerIconUrl: string | null;
	category: string | null;
	entrypoint: string;
};

/** Legacy /api/catalog/functions list shape (was served live by fn-activepieces). */
export async function listPieceCatalogFunctions(): Promise<PieceCatalogFunctionSummary[]> {
	const { actions } = await loadPieceMetadataActionSource();
	return actions.map((action) => ({
		name: action.name,
		version: action.version || '1.0.0',
		displayName: action.displayName,
		description: action.description,
		pieceName: action.providerId || action.group,
		actionName: action.entrypoint || action.slug,
		providerId: action.providerId || action.group,
		providerLabel: action.providerLabel || action.group,
		providerIconUrl: action.providerIconUrl ?? null,
		category: action.category ?? null,
		entrypoint: action.entrypoint || action.slug,
	}));
}

/**
 * Legacy /api/catalog/functions/[name]/[version] definition lookup. Version is
 * intentionally ignored: the retired fn-activepieces catalog hardcoded
 * "1.0.0" while piece_metadata carries real piece versions.
 */
export async function getPieceCatalogDefinition(
	name: string,
): Promise<Record<string, unknown> | null> {
	const { actions } = await loadPieceMetadataActionSource();
	const match = actions.find((action) => action.name === name);
	return match?.sw.definition ?? null;
}
