/**
 * Python emitter — mirrors emit-ts.ts using Python idioms (async def, async
 * for, try/except). Produces a runnable .py file whose entrypoint is `main`.
 */

import type {
	EmitNode,
	EmitWorkflowInput,
	InlinedFunction,
	CallNode,
} from './ir';
import { classifyJq, pyStringLiteral } from './jq-to-lang';
import type { JqMarker } from './normalize';
import { markJqExpressions } from './normalize';

export interface PyEmitResult {
	source: string;
	warnings: string[];
	supportingFiles: Record<string, string>;
}

export function emitPython(
	input: EmitWorkflowInput,
	shimSource: string,
): PyEmitResult {
	const warnings = [...input.warnings];
	const lines: string[] = [];
	const supportingFiles: Record<string, string> = {};

	lines.push(buildHeader(input));
	lines.push('');
	lines.push('import asyncio');
	lines.push('import json');
	lines.push('import sys');
	lines.push('from typing import Any');
	lines.push('');
	lines.push('from runtime import WorkflowContext, run_workflow');
	lines.push('');

	for (const fn of input.inlinedFunctions) {
		if (fn.language !== 'python') {
			warnings.push(
				`Skipping inline of "${fn.slug}" (language=${fn.language}) — language mismatch with Python emission; call will dispatch via shim.`,
			);
			continue;
		}
		lines.push(inlineBanner(fn));
		lines.push(fn.sourceSnippet);
		lines.push('');
		for (const [path, contents] of Object.entries(fn.supportingFiles)) {
			const prefixed = `_inlined/${fn.slug}/${path}`;
			supportingFiles[prefixed] = contents;
		}
	}

	lines.push('');
	lines.push('async def main(trigger: dict[str, Any], ctx: WorkflowContext) -> Any:');
	if (input.steps.length === 0) {
		lines.push('\treturn ctx.state');
	} else {
		for (const node of input.steps) {
			for (const line of emitNode(node, 1, warnings, input.inlinedFunctions)) {
				lines.push(line);
			}
		}
		lines.push('\treturn ctx.state');
	}
	lines.push('');
	lines.push(
		'__workflow_spec__ = ' + pyLiteral(input.originalSpec, '') + '',
	);
	lines.push('');
	lines.push('if __name__ == "__main__":');
	lines.push('\ttrigger = json.loads(sys.argv[1] if len(sys.argv) > 1 else "{}")');
	lines.push('\tout = asyncio.run(run_workflow(lambda ctx: main(trigger, ctx), trigger))');
	lines.push('\tsys.stdout.write(json.dumps(out))');

	return {
		source: lines.join('\n') + '\n',
		warnings,
		supportingFiles: {
			'runtime.py': shimSource,
			...supportingFiles,
		},
	};
}

function buildHeader(input: EmitWorkflowInput): string {
	return [
		`"""`,
		`Emitted from workflow "${input.workflowName.replace(/"/g, '\\"')}".`,
		`DO NOT EDIT THIS FILE MANUALLY — re-emit via GET /api/workflows/<id>/export.`,
		``,
		`The original SW 1.0 spec is preserved at the bottom of this file as`,
		`\`__workflow_spec__\` so the visual graph can be reconstructed by tooling.`,
		`"""`,
	].join('\n');
}

function inlineBanner(fn: InlinedFunction): string {
	return [
		`# ──────────────────────────────────────────────────────────────────────`,
		`# inlined: code/${fn.slug} @ ${fn.version} (sha1:${fn.sha})`,
		`# identifier: ${fn.identifier}`,
		`# ──────────────────────────────────────────────────────────────────────`,
	].join('\n');
}

function emitNode(
	node: EmitNode,
	indent: number,
	warnings: string[],
	inlined: InlinedFunction[],
): string[] {
	const pad = '\t'.repeat(indent);
	switch (node.kind) {
		case 'call':
			return emitCall(node, pad, warnings, inlined);
		case 'set':
			return emitSet(node, pad, warnings);
		case 'switch':
			return emitSwitch(node, pad, warnings);
		case 'for':
			return emitFor(node, indent, warnings, inlined);
		case 'try':
			return emitTry(node, indent, warnings, inlined);
		case 'wait':
			return [`${pad}await ctx.sleep(${pyStringLiteral(node.duration)})`];
		case 'do':
			return [
				`${pad}# do: ${node.taskName}`,
				...node.steps.flatMap((step) =>
					emitNode(step, indent, warnings, inlined),
				),
			];
		case 'passthrough':
			return emitPassthrough(node.taskName, node.taskKind, node.raw, node.reason, pad);
	}
}

function emitCall(
	node: CallNode,
	pad: string,
	warnings: string[],
	inlined: InlinedFunction[],
): string[] {
	const argsLiteral = renderArgs(node.args, warnings);
	const binding = `${node.taskName}`;
	if (node.inlined) {
		const fn = inlined.find((f) => f.identifier === node.inlined?.identifier);
		if (fn && fn.language === 'python') {
			return [`${pad}${binding} = await ${node.inlined.identifier}(${argsLiteral})`];
		}
	}
	return [
		`${pad}${binding} = await ctx.call_activity(${pyStringLiteral(
			node.slug,
		)}, ${argsLiteral})`,
	];
}

function emitSet(
	node: { assignments: Record<string, unknown> },
	pad: string,
	warnings: string[],
): string[] {
	const marked = markJqExpressions(node.assignments) as Record<string, unknown>;
	const obj = renderMarkedValue(marked, warnings);
	return [`${pad}ctx.set_state(${obj})`];
}

function emitSwitch(
	node: {
		cases: Array<{ when: string | null; then: string }>;
		taskName: string;
	},
	pad: string,
	warnings: string[],
): string[] {
	const lines: string[] = [];
	let isFirst = true;
	for (const c of node.cases) {
		if (c.when) {
			const classified = classifyJq(c.when);
			if (!classified.supported) {
				warnings.push(
					`Switch "${node.taskName}" condition "${c.when}" uses an unsupported jq form; shim will log at runtime.`,
				);
			}
			const keyword = isFirst ? 'if' : 'elif';
			lines.push(
				`${pad}${keyword} await ctx.jq_bool(${pyStringLiteral(classified.expression)}):`,
			);
		} else {
			lines.push(`${pad}else:`);
		}
		lines.push(`${pad}\t# then: ${c.then}`);
		if (c.then === 'end') lines.push(`${pad}\treturn ctx.state`);
		else if (c.then !== 'continue')
			lines.push(`${pad}\tpass  # TODO(emitter): jump to task "${c.then}" not yet wired`);
		else lines.push(`${pad}\tpass`);
		isFirst = false;
	}
	return lines;
}

function emitFor(
	node: { each: string; in: string; body: EmitNode[] },
	indent: number,
	warnings: string[],
	inlined: InlinedFunction[],
): string[] {
	const pad = '\t'.repeat(indent);
	const classified = classifyJq(node.in);
	if (!classified.supported) {
		warnings.push(
			`For-loop iterable "${node.in}" is outside the supported jq subset.`,
		);
	}
	const body = node.body.flatMap((step) =>
		emitNode(step, indent + 1, warnings, inlined),
	);
	return [
		`${pad}for ${node.each} in await ctx.jq_array(${pyStringLiteral(classified.expression)}):`,
		`${pad}\tctx.set_state({${pyStringLiteral(node.each)}: ${node.each}})`,
		...(body.length > 0 ? body : [`${pad}\tpass`]),
	];
}

function emitTry(
	node: {
		tryBody: EmitNode[];
		catchBody: EmitNode[] | null;
		catchWhen: string | null;
	},
	indent: number,
	warnings: string[],
	inlined: InlinedFunction[],
): string[] {
	const pad = '\t'.repeat(indent);
	const lines: string[] = [];
	lines.push(`${pad}try:`);
	const body = node.tryBody.flatMap((step) =>
		emitNode(step, indent + 1, warnings, inlined),
	);
	lines.push(...(body.length > 0 ? body : [`${pad}\tpass`]));
	lines.push(`${pad}except Exception as e:`);
	if (node.catchBody) {
		if (node.catchWhen) {
			const classified = classifyJq(node.catchWhen);
			if (!classified.supported) {
				warnings.push(`Catch filter "${node.catchWhen}" is outside the supported jq subset.`);
			}
			lines.push(
				`${pad}\tif ctx.error_matches_jq(e, ${pyStringLiteral(classified.expression)}):`,
			);
			const catchBody = node.catchBody.flatMap((step) =>
				emitNode(step, indent + 2, warnings, inlined),
			);
			lines.push(...(catchBody.length > 0 ? catchBody : [`${pad}\t\tpass`]));
			lines.push(`${pad}\telse:`);
			lines.push(`${pad}\t\traise`);
		} else {
			const catchBody = node.catchBody.flatMap((step) =>
				emitNode(step, indent + 1, warnings, inlined),
			);
			lines.push(...(catchBody.length > 0 ? catchBody : [`${pad}\tpass`]));
		}
	} else {
		lines.push(`${pad}\traise`);
	}
	return lines;
}

function emitPassthrough(
	taskName: string,
	taskKind: string,
	raw: unknown,
	reason: string,
	pad: string,
): string[] {
	return [
		`${pad}# TODO(emitter): ${taskKind} passthrough — ${reason}`,
		`${pad}__raw_${taskName} = ${pyLiteral(raw, '')}`,
		`${pad}await ctx.call_unsupported_task(${pyStringLiteral(taskKind)}, __raw_${taskName})`,
	];
}

function renderArgs(args: unknown, warnings: string[]): string {
	const marked = markJqExpressions(args);
	return renderMarkedValue(marked, warnings);
}

function renderMarkedValue(value: unknown, warnings: string[]): string {
	if (value === null) return 'None';
	if (value === undefined) return 'None';
	if (typeof value === 'string') return pyStringLiteral(value);
	if (typeof value === 'number') return String(value);
	if (typeof value === 'boolean') return value ? 'True' : 'False';
	if (Array.isArray(value)) {
		return `[${value.map((v) => renderMarkedValue(v, warnings)).join(', ')}]`;
	}
	if (typeof value === 'object') {
		const marker = value as JqMarker;
		if (typeof marker.__jq === 'string') {
			const classified = classifyJq(marker.__jq);
			if (!classified.supported) {
				warnings.push(
					`jq expression "${marker.__jq}" is outside the supported subset.`,
				);
			}
			return `ctx.jq(${pyStringLiteral(classified.expression)})`;
		}
		const entries = Object.entries(value as Record<string, unknown>).map(
			([key, v]) => `${pyStringLiteral(key)}: ${renderMarkedValue(v, warnings)}`,
		);
		return `{${entries.join(', ')}}`;
	}
	return 'None';
}

function pyLiteral(value: unknown, indent: string): string {
	if (value === null || value === undefined) return 'None';
	if (typeof value === 'string') return pyStringLiteral(value);
	if (typeof value === 'number') return String(value);
	if (typeof value === 'boolean') return value ? 'True' : 'False';
	if (Array.isArray(value)) {
		return `[${value.map((v) => pyLiteral(v, indent)).join(', ')}]`;
	}
	if (typeof value === 'object') {
		const entries = Object.entries(value as Record<string, unknown>).map(
			([key, v]) => `${pyStringLiteral(key)}: ${pyLiteral(v, indent)}`,
		);
		return `{${entries.join(', ')}}`;
	}
	return 'None';
}
