/**
 * TypeScript emitter — walks an EmitNode[] and produces a runnable .ts file.
 *
 * Emission model:
 *   - One top-level async function `main(trigger, ctx)` contains the workflow
 *     body (the normalized do-array). Each task maps to a statement.
 *   - Inlined code_functions appear ABOVE main() as `async function <id>(args)`.
 *   - Shim is imported from `./runtime.ts` (vendored as a supporting file).
 *   - A `__workflowSpec` const at the bottom carries the original SW 1.0 JSON
 *     so future tooling can reconstruct the visual graph.
 */

import type {
	EmitNode,
	EmitWorkflowInput,
	InlinedFunction,
	CallNode,
} from './ir';
import { classifyJq, jsStringLiteral } from './jq-to-lang';
import type { JqMarker } from './normalize';
import { markJqExpressions } from './normalize';

export interface EmitResult {
	source: string;
	warnings: string[];
	supportingFiles: Record<string, string>;
}

export function emitTypeScript(
	input: EmitWorkflowInput,
	shimSource: string,
): EmitResult {
	const warnings = [...input.warnings];
	const lines: string[] = [];
	const supportingFiles: Record<string, string> = {};

	lines.push(buildHeader(input));
	lines.push('');
	lines.push(`import { WorkflowContext, runWorkflow } from "./runtime";`);
	lines.push('');

	for (const fn of input.inlinedFunctions) {
		if (fn.language !== 'typescript') {
			warnings.push(
				`Skipping inline of "${fn.slug}" (language=${fn.language}) — language mismatch with TypeScript emission; call will dispatch via shim.`,
			);
			continue;
		}
		lines.push(inlineBanner(fn));
		lines.push(fn.sourceSnippet);
		lines.push('');
		for (const [path, contents] of Object.entries(fn.supportingFiles)) {
			const prefixed = `_inlined/${fn.slug}/${path}`;
			supportingFiles[prefixed] = contents;
		}
	}

	lines.push(buildTriggerType(input.triggerSchema));
	lines.push('');
	lines.push('export async function main(');
	lines.push('\ttrigger: TriggerInput,');
	lines.push('\tctx: WorkflowContext,');
	lines.push('): Promise<unknown> {');
	for (const node of input.steps) {
		for (const line of emitNode(node, 1, warnings, input.inlinedFunctions)) {
			lines.push(line);
		}
	}
	lines.push('\treturn ctx.state;');
	lines.push('}');
	lines.push('');
	lines.push(
		'export const __workflowSpec = ' + JSON.stringify(input.originalSpec, null, 2) + ' as const;',
	);
	lines.push('');
	lines.push('if (typeof require !== "undefined" && require.main === module) {');
	lines.push(
		'\tconst trigger = JSON.parse(process.argv[2] || "{}") as TriggerInput;',
	);
	lines.push(
		'\trunWorkflow((ctx) => main(trigger, ctx), trigger).then((out) => {',
	);
	lines.push('\t\tprocess.stdout.write(JSON.stringify(out));');
	lines.push('\t}).catch((err) => {');
	lines.push(
		'\t\tprocess.stderr.write(err instanceof Error ? err.stack ?? err.message : String(err));',
	);
	lines.push('\t\tprocess.exit(1);');
	lines.push('\t});');
	lines.push('}');

	return {
		source: lines.join('\n') + '\n',
		warnings,
		supportingFiles: {
			'runtime.ts': shimSource,
			...supportingFiles,
		},
	};
}

function buildHeader(input: EmitWorkflowInput): string {
	return [
		`/**`,
		` * Emitted from workflow "${escapeComment(input.workflowName)}".`,
		` * DO NOT EDIT THIS FILE MANUALLY — re-emit via GET /api/workflows/<id>/export.`,
		` *`,
		` * The original SW 1.0 spec is preserved at the bottom of this file as`,
		` * \`__workflowSpec\` so the visual graph can be reconstructed by tooling.`,
		` */`,
	].join('\n');
}

function inlineBanner(fn: InlinedFunction): string {
	return [
		`// ──────────────────────────────────────────────────────────────────────`,
		`// inlined: code/${fn.slug} @ ${fn.version} (sha1:${fn.sha})`,
		`// identifier: ${fn.identifier}`,
		`// ──────────────────────────────────────────────────────────────────────`,
	].join('\n');
}

function buildTriggerType(schema: Record<string, unknown> | null): string {
	if (!schema) return 'export type TriggerInput = Record<string, unknown>;';
	return `export type TriggerInput = ${renderJsonSchemaAsType(schema)};`;
}

function renderJsonSchemaAsType(schema: Record<string, unknown>): string {
	const type = (schema.type as string | string[] | undefined) ?? undefined;
	const enumValues = schema.enum as unknown[] | undefined;
	if (enumValues && enumValues.length > 0) {
		return enumValues.map((v) => JSON.stringify(v)).join(' | ');
	}
	if (Array.isArray(type)) {
		return type.map((t) => renderPrimitive(t)).join(' | ');
	}
	if (type === 'object') {
		const props = (schema.properties as Record<string, unknown> | undefined) ?? {};
		const required = new Set((schema.required as string[] | undefined) ?? []);
		const entries = Object.entries(props).map(([key, prop]) => {
			const optional = required.has(key) ? '' : '?';
			const valueType =
				typeof prop === 'object' && prop !== null
					? renderJsonSchemaAsType(prop as Record<string, unknown>)
					: 'unknown';
			return `\t${JSON.stringify(key)}${optional}: ${valueType};`;
		});
		if (entries.length === 0) return 'Record<string, unknown>';
		return `{\n${entries.join('\n')}\n}`;
	}
	if (type === 'array') {
		const items = schema.items;
		const inner =
			typeof items === 'object' && items !== null
				? renderJsonSchemaAsType(items as Record<string, unknown>)
				: 'unknown';
		return `Array<${inner}>`;
	}
	return renderPrimitive(typeof type === 'string' ? type : 'unknown');
}

function renderPrimitive(t: string): string {
	switch (t) {
		case 'string':
			return 'string';
		case 'integer':
		case 'number':
			return 'number';
		case 'boolean':
			return 'boolean';
		case 'null':
			return 'null';
		default:
			return 'unknown';
	}
}

function emitNode(
	node: EmitNode,
	indent: number,
	warnings: string[],
	inlined: InlinedFunction[],
): string[] {
	const pad = '\t'.repeat(indent);

	switch (node.kind) {
		case 'call':
			return emitCall(node, pad, warnings, inlined);
		case 'set':
			return emitSet(node, pad, warnings);
		case 'switch':
			return emitSwitch(node, pad, warnings);
		case 'for':
			return emitFor(node, indent, warnings, inlined);
		case 'try':
			return emitTry(node, indent, warnings, inlined);
		case 'wait':
			return [`${pad}await ctx.sleep(${jsStringLiteral(node.duration)});`];
		case 'do':
			return [
				`${pad}{ // do: ${node.taskName}`,
				...node.steps.flatMap((step) =>
					emitNode(step, indent + 1, warnings, inlined),
				),
				`${pad}}`,
			];
		case 'passthrough':
			return emitPassthrough(node.taskName, node.taskKind, node.raw, node.reason, pad);
	}
}

function emitCall(
	node: CallNode,
	pad: string,
	warnings: string[],
	inlined: InlinedFunction[],
): string[] {
	const argsLiteral = renderArgs(node.args, warnings);
	const binding = `const ${node.taskName}`;
	if (node.inlined) {
		const fn = inlined.find((f) => f.identifier === node.inlined?.identifier);
		if (fn && fn.language === 'typescript') {
			return [`${pad}${binding} = await ${node.inlined.identifier}(${argsLiteral});`];
		}
	}
	return [
		`${pad}${binding} = await ctx.callActivity(${jsStringLiteral(
			node.slug,
		)}, ${argsLiteral});`,
	];
}

function emitSet(node: { assignments: Record<string, unknown> }, pad: string, warnings: string[]): string[] {
	const marked = markJqExpressions(node.assignments) as Record<string, unknown>;
	const obj = renderMarkedValue(marked, warnings);
	return [`${pad}ctx.setState(${obj});`];
}

function emitSwitch(
	node: { cases: Array<{ when: string | null; then: string }>; taskName: string },
	pad: string,
	warnings: string[],
): string[] {
	const lines: string[] = [];
	let isFirst = true;
	for (const c of node.cases) {
		if (c.when) {
			const classified = classifyJq(c.when);
			if (!classified.supported) {
				warnings.push(
					`Switch "${node.taskName}" condition "${c.when}" uses an unsupported jq form; shim will log at runtime.`,
				);
			}
			const keyword = isFirst ? 'if' : 'else if';
			lines.push(
				`${pad}${keyword} (await ctx.jqBool(${jsStringLiteral(classified.expression)})) {`,
			);
		} else {
			lines.push(`${pad}else {`);
		}
		lines.push(`${pad}\t// then: ${c.then}`);
		if (c.then === 'end') lines.push(`${pad}\treturn ctx.state;`);
		else if (c.then !== 'continue')
			lines.push(`${pad}\t// TODO(emitter): jump to task "${c.then}" not yet wired`);
		lines.push(`${pad}}`);
		isFirst = false;
	}
	return lines;
}

function emitFor(
	node: { each: string; in: string; body: EmitNode[] },
	indent: number,
	warnings: string[],
	inlined: InlinedFunction[],
): string[] {
	const pad = '\t'.repeat(indent);
	const classified = classifyJq(node.in);
	if (!classified.supported) {
		warnings.push(
			`For-loop iterable "${node.in}" is outside the supported jq subset.`,
		);
	}
	return [
		`${pad}for (const ${node.each} of await ctx.jqArray(${jsStringLiteral(classified.expression)})) {`,
		`${pad}\tctx.setState({ ${node.each} });`,
		...node.body.flatMap((step) => emitNode(step, indent + 1, warnings, inlined)),
		`${pad}}`,
	];
}

function emitTry(
	node: { tryBody: EmitNode[]; catchBody: EmitNode[] | null; catchWhen: string | null },
	indent: number,
	warnings: string[],
	inlined: InlinedFunction[],
): string[] {
	const pad = '\t'.repeat(indent);
	const lines: string[] = [];
	lines.push(`${pad}try {`);
	for (const step of node.tryBody)
		lines.push(...emitNode(step, indent + 1, warnings, inlined));
	lines.push(`${pad}} catch (e) {`);
	if (node.catchBody) {
		if (node.catchWhen) {
			const classified = classifyJq(node.catchWhen);
			if (!classified.supported) {
				warnings.push(`Catch filter "${node.catchWhen}" is outside the supported jq subset.`);
			}
			lines.push(`${pad}\tif (ctx.errorMatchesJq(e, ${jsStringLiteral(classified.expression)})) {`);
			for (const step of node.catchBody)
				lines.push(...emitNode(step, indent + 2, warnings, inlined));
			lines.push(`${pad}\t} else { throw e; }`);
		} else {
			for (const step of node.catchBody)
				lines.push(...emitNode(step, indent + 1, warnings, inlined));
		}
	} else {
		lines.push(`${pad}\tthrow e;`);
	}
	lines.push(`${pad}}`);
	return lines;
}

function emitPassthrough(
	taskName: string,
	taskKind: string,
	raw: unknown,
	reason: string,
	pad: string,
): string[] {
	return [
		`${pad}// TODO(emitter): ${taskKind} passthrough — ${reason}`,
		`${pad}const __raw_${taskName} = ${JSON.stringify(raw)};`,
		`${pad}await ctx.callUnsupportedTask(${jsStringLiteral(taskKind)}, __raw_${taskName});`,
	];
}

function renderArgs(args: unknown, warnings: string[]): string {
	const marked = markJqExpressions(args);
	return renderMarkedValue(marked, warnings);
}

function renderMarkedValue(value: unknown, warnings: string[]): string {
	if (value === null) return 'null';
	if (value === undefined) return 'undefined';
	if (typeof value === 'string') return JSON.stringify(value);
	if (typeof value === 'number' || typeof value === 'boolean') return String(value);
	if (Array.isArray(value)) {
		return `[${value.map((v) => renderMarkedValue(v, warnings)).join(', ')}]`;
	}
	if (typeof value === 'object') {
		const marker = value as JqMarker;
		if (typeof marker.__jq === 'string') {
			const classified = classifyJq(marker.__jq);
			if (!classified.supported) {
				warnings.push(
					`jq expression "${marker.__jq}" is outside the supported subset.`,
				);
			}
			return `ctx.jq(${jsStringLiteral(classified.expression)})`;
		}
		const entries = Object.entries(value as Record<string, unknown>).map(
			([key, v]) => `${JSON.stringify(key)}: ${renderMarkedValue(v, warnings)}`,
		);
		return `{ ${entries.join(', ')} }`;
	}
	return 'null';
}

function escapeComment(value: string): string {
	return value.replace(/\*\//g, '*\\/');
}
