/**
 * Step Registry (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * This registry enables dynamic step imports that are statically analyzable
 * by the bundler. Each action type maps to its step importer function.
 *
 * Generated entries: 36
 */

import "server-only";

// biome-ignore lint/suspicious/noExplicitAny: Dynamic step module types - step functions take any input
export type StepFunction = (input: any) => Promise<any>;

// Step modules may contain the step function plus other exports (types, constants, etc.)
// biome-ignore lint/suspicious/noExplicitAny: Dynamic module with mixed exports
export type StepModule = Record<string, any>;

export type StepImporter = {
	importer: () => Promise<StepModule>;
	stepFunction: string;
};

function importStep(path: string): Promise<StepModule> {
	// Avoid TypeScript module resolution errors when step modules are not present
	// in this repo checkout. If/when these modules exist, runtime behavior is
	// unchanged (a dynamic import of the same path).
	return import(path) as Promise<StepModule>;
}

/**
 * Plugin step importers - maps action types to their step import functions
 * These imports are statically analyzable by the bundler
 */
export const PLUGIN_STEP_IMPORTERS: Record<string, StepImporter> = {
	"blob/put": {
		importer: () => importStep("@/plugins/blob/steps/put"),
		stepFunction: "putBlobStep",
	},
	"blob/list": {
		importer: () => importStep("@/plugins/blob/steps/list"),
		stepFunction: "listBlobsStep",
	},
	"clerk/get-user": {
		importer: () => importStep("@/plugins/clerk/steps/get-user"),
		stepFunction: "clerkGetUserStep",
	},
	"clerk/create-user": {
		importer: () => importStep("@/plugins/clerk/steps/create-user"),
		stepFunction: "clerkCreateUserStep",
	},
	"clerk/update-user": {
		importer: () => importStep("@/plugins/clerk/steps/update-user"),
		stepFunction: "clerkUpdateUserStep",
	},
	"clerk/delete-user": {
		importer: () => importStep("@/plugins/clerk/steps/delete-user"),
		stepFunction: "clerkDeleteUserStep",
	},
	"fal/generate-image": {
		importer: () => importStep("@/plugins/fal/steps/generate-image"),
		stepFunction: "falGenerateImageStep",
	},
	"fal/generate-video": {
		importer: () => importStep("@/plugins/fal/steps/generate-video"),
		stepFunction: "falGenerateVideoStep",
	},
	"fal/upscale-image": {
		importer: () => importStep("@/plugins/fal/steps/upscale-image"),
		stepFunction: "falUpscaleImageStep",
	},
	"fal/remove-background": {
		importer: () => importStep("@/plugins/fal/steps/remove-background"),
		stepFunction: "falRemoveBackgroundStep",
	},
	"fal/image-to-image": {
		importer: () => importStep("@/plugins/fal/steps/image-to-image"),
		stepFunction: "falImageToImageStep",
	},
	"firecrawl/scrape": {
		importer: () => importStep("@/plugins/firecrawl/steps/scrape"),
		stepFunction: "firecrawlScrapeStep",
	},
	Scrape: {
		importer: () => importStep("@/plugins/firecrawl/steps/scrape"),
		stepFunction: "firecrawlScrapeStep",
	},
	"firecrawl/search": {
		importer: () => importStep("@/plugins/firecrawl/steps/search"),
		stepFunction: "firecrawlSearchStep",
	},
	Search: {
		importer: () => importStep("@/plugins/firecrawl/steps/search"),
		stepFunction: "firecrawlSearchStep",
	},
	"github/create-issue": {
		importer: () => importStep("@/plugins/github/steps/create-issue"),
		stepFunction: "createIssueStep",
	},
	create_issue: {
		importer: () => importStep("@/plugins/github/steps/create-issue"),
		stepFunction: "createIssueStep",
	},
	"github/list-issues": {
		importer: () => importStep("@/plugins/github/steps/list-issues"),
		stepFunction: "listIssuesStep",
	},
	list_issues: {
		importer: () => importStep("@/plugins/github/steps/list-issues"),
		stepFunction: "listIssuesStep",
	},
	"github/get-issue": {
		importer: () => importStep("@/plugins/github/steps/get-issue"),
		stepFunction: "getIssueStep",
	},
	get_issue: {
		importer: () => importStep("@/plugins/github/steps/get-issue"),
		stepFunction: "getIssueStep",
	},
	"github/update-issue": {
		importer: () => importStep("@/plugins/github/steps/update-issue"),
		stepFunction: "updateIssueStep",
	},
	"linear/create-ticket": {
		importer: () => importStep("@/plugins/linear/steps/create-ticket"),
		stepFunction: "createTicketStep",
	},
	create_ticket: {
		importer: () => importStep("@/plugins/linear/steps/create-ticket"),
		stepFunction: "createTicketStep",
	},
	"Create Ticket": {
		importer: () => importStep("@/plugins/linear/steps/create-ticket"),
		stepFunction: "createTicketStep",
	},
	"linear/find-issues": {
		importer: () => importStep("@/plugins/linear/steps/find-issues"),
		stepFunction: "findIssuesStep",
	},
	find_issues: {
		importer: () => importStep("@/plugins/linear/steps/find-issues"),
		stepFunction: "findIssuesStep",
	},
	"Find Issues": {
		importer: () => importStep("@/plugins/linear/steps/find-issues"),
		stepFunction: "findIssuesStep",
	},
	"openai/generate-text": {
		importer: () => importStep("@/plugins/openai/steps/generate-text"),
		stepFunction: "generateTextStep",
	},
	"Generate Text": {
		importer: () => importStep("@/plugins/openai/steps/generate-text"),
		stepFunction: "generateTextStep",
	},
	"ai-gateway/generate-text": {
		importer: () => importStep("@/plugins/openai/steps/generate-text"),
		stepFunction: "generateTextStep",
	},
	generate_text: {
		importer: () => importStep("@/plugins/openai/steps/generate-text"),
		stepFunction: "generateTextStep",
	},
	"openai/generate-image": {
		importer: () => importStep("@/plugins/openai/steps/generate-image"),
		stepFunction: "generateImageStep",
	},
	"Generate Image": {
		importer: () => importStep("@/plugins/openai/steps/generate-image"),
		stepFunction: "generateImageStep",
	},
	"ai-gateway/generate-image": {
		importer: () => importStep("@/plugins/openai/steps/generate-image"),
		stepFunction: "generateImageStep",
	},
	generate_image: {
		importer: () => importStep("@/plugins/openai/steps/generate-image"),
		stepFunction: "generateImageStep",
	},
	"perplexity/search": {
		importer: () => importStep("@/plugins/perplexity/steps/search"),
		stepFunction: "perplexitySearchStep",
	},
	"perplexity/ask": {
		importer: () => importStep("@/plugins/perplexity/steps/ask"),
		stepFunction: "perplexityAskStep",
	},
	"perplexity/research": {
		importer: () => importStep("@/plugins/perplexity/steps/research"),
		stepFunction: "perplexityResearchStep",
	},
	"resend/send-email": {
		importer: () => importStep("@/plugins/resend/steps/send-email"),
		stepFunction: "sendEmailStep",
	},
	send_email: {
		importer: () => importStep("@/plugins/resend/steps/send-email"),
		stepFunction: "sendEmailStep",
	},
	"Send Email": {
		importer: () => importStep("@/plugins/resend/steps/send-email"),
		stepFunction: "sendEmailStep",
	},
	"slack/send-message": {
		importer: () => importStep("@/plugins/slack/steps/send-slack-message"),
		stepFunction: "sendSlackMessageStep",
	},
	send_message: {
		importer: () => importStep("@/plugins/slack/steps/send-slack-message"),
		stepFunction: "sendSlackMessageStep",
	},
	"Send Slack Message": {
		importer: () => importStep("@/plugins/slack/steps/send-slack-message"),
		stepFunction: "sendSlackMessageStep",
	},
	"stripe/create-customer": {
		importer: () => importStep("@/plugins/stripe/steps/create-customer"),
		stepFunction: "createCustomerStep",
	},
	"stripe/get-customer": {
		importer: () => importStep("@/plugins/stripe/steps/get-customer"),
		stepFunction: "getCustomerStep",
	},
	"stripe/create-invoice": {
		importer: () => importStep("@/plugins/stripe/steps/create-invoice"),
		stepFunction: "createInvoiceStep",
	},
	"superagent/guard": {
		importer: () => importStep("@/plugins/superagent/steps/guard"),
		stepFunction: "superagentGuardStep",
	},
	"superagent/redact": {
		importer: () => importStep("@/plugins/superagent/steps/redact"),
		stepFunction: "superagentRedactStep",
	},
	"v0/create-chat": {
		importer: () => importStep("@/plugins/v0/steps/create-chat"),
		stepFunction: "createChatStep",
	},
	"Create Chat": {
		importer: () => importStep("@/plugins/v0/steps/create-chat"),
		stepFunction: "createChatStep",
	},
	"v0/send-message": {
		importer: () => importStep("@/plugins/v0/steps/send-message"),
		stepFunction: "sendMessageStep",
	},
	"Send Message": {
		importer: () => importStep("@/plugins/v0/steps/send-message"),
		stepFunction: "sendMessageStep",
	},
	"webflow/list-sites": {
		importer: () => importStep("@/plugins/webflow/steps/list-sites"),
		stepFunction: "listSitesStep",
	},
	"webflow/get-site": {
		importer: () => importStep("@/plugins/webflow/steps/get-site"),
		stepFunction: "getSiteStep",
	},
	"webflow/publish-site": {
		importer: () => importStep("@/plugins/webflow/steps/publish-site"),
		stepFunction: "publishSiteStep",
	},
};

/**
 * Action labels - maps action IDs to human-readable labels
 * Used for displaying friendly names in the UI (e.g., Runs tab)
 */
export const ACTION_LABELS: Record<string, string> = {
	"blob/put": "Put Blob",
	"blob/list": "List Blobs",
	"clerk/get-user": "Get User",
	"clerk/create-user": "Create User",
	"clerk/update-user": "Update User",
	"clerk/delete-user": "Delete User",
	"fal/generate-image": "Generate Image",
	"fal/generate-video": "Generate Video",
	"fal/upscale-image": "Upscale Image",
	"fal/remove-background": "Remove Background",
	"fal/image-to-image": "Image to Image",
	"firecrawl/scrape": "Scrape URL",
	"firecrawl/search": "Search Web",
	"github/create-issue": "Create Issue",
	"github/list-issues": "List Issues",
	"github/get-issue": "Get Issue",
	"github/update-issue": "Update Issue",
	"linear/create-ticket": "Create Ticket",
	"linear/find-issues": "Find Issues",
	"openai/generate-text": "Generate Text",
	"openai/generate-image": "Generate Image",
	"perplexity/search": "Search Web",
	"perplexity/ask": "Ask Question",
	"perplexity/research": "Research Topic",
	"resend/send-email": "Send Email",
	"slack/send-message": "Send Slack Message",
	"stripe/create-customer": "Create Customer",
	"stripe/get-customer": "Get Customer",
	"stripe/create-invoice": "Create Invoice",
	"superagent/guard": "Guard",
	"superagent/redact": "Redact",
	"v0/create-chat": "Create Chat",
	"v0/send-message": "Send Message",
	"webflow/list-sites": "List Sites",
	"webflow/get-site": "Get Site",
	"webflow/publish-site": "Publish Site",
	Scrape: "Scrape URL",
	Search: "Search Web",
	"Generate Text": "Generate Text",
	"ai-gateway/generate-text": "Generate Text",
	generate_text: "Generate Text",
	"Generate Image": "Generate Image",
	"ai-gateway/generate-image": "Generate Image",
	generate_image: "Generate Image",
	create_issue: "Create Issue",
	list_issues: "List Issues",
	get_issue: "Get Issue",
	send_message: "Send Slack Message",
	"Send Slack Message": "Send Slack Message",
	send_email: "Send Email",
	"Send Email": "Send Email",
	create_ticket: "Create Ticket",
	"Create Ticket": "Create Ticket",
	find_issues: "Find Issues",
	"Find Issues": "Find Issues",
	"Create Chat": "Create Chat",
	"Send Message": "Send Message",
};

/**
 * Get a step importer for an action type
 */
export function getStepImporter(actionType: string): StepImporter | undefined {
	return PLUGIN_STEP_IMPORTERS[actionType];
}

/**
 * Get the human-readable label for an action type
 */
export function getActionLabel(actionType: string): string | undefined {
	return ACTION_LABELS[actionType];
}
