/**
 * Generates services/shared/contracts/script-evaluator-callid-vectors.json by
 * ACTUALLY RUNNING the evaluator on a fixed set of scripts. These vectors pin
 * the FROZEN callId derivation (baseHash + occurrence) so the orchestrator
 * pytest suite (and any future re-implementation) can assert byte-for-byte
 * agreement without importing this Node code.
 *
 * Run: pnpm gen:vectors   (requires --experimental-vm-modules)
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { EVALUATOR_VERSION, evaluateScript } from "../src/sandbox.js";

interface VectorCase {
	description: string;
	script: string;
}

const META = (name: string) =>
	`export const meta = { name: '${name}', description: 'callId vector', phases: [{ title: 'main' }] }\n`;

const CASES: VectorCase[] = [
	{
		description: "simple agent() call",
		script: META("simple-agent") + "phase('main')\nconst a = await agent('summarize the input')\nreturn { a }",
	},
	{
		description: "agent() with a schema (schema participates in baseHash)",
		script:
			META("schema-agent") +
			"const a = await agent('extract fields', { schema: { type: 'object', properties: { title: { type: 'string' } } }, label: 'extract' })\nreturn { a }",
	},
	{
		description: "duplicate prompt+opts → occurrence counter increments per baseHash",
		script:
			META("dup-agent") +
			"const r = await parallel([\n  () => agent('do it', { label: 'L' }),\n  () => agent('do it', { label: 'L' }),\n  () => agent('do it', { label: 'L' }),\n])\nreturn { r }",
	},
	{
		description: "labeled pipeline() calls across two stages",
		script:
			META("labeled-pipeline") +
			"const r = await pipeline(['x', 'y'],\n  async (item) => await agent('stage-one', { label: 'first:' + item }),\n  async (val) => await agent('stage-two', { label: 'second' }),\n)\nreturn { r }",
	},
	{
		description: "workflow() call (kind=workflow, prompt='', workflowRef/args)",
		script:
			META("workflow-call") +
			"const r = await workflow('child-report', { region: 'emea', year: 2026 })\nreturn { r }",
	},
	{
		description: "parallel() batch of distinct agent() calls",
		script:
			META("parallel-batch") +
			"const r = await parallel([\n  () => agent('alpha'),\n  () => agent('beta'),\n  () => agent('gamma'),\n])\nreturn { r }",
	},
];

async function main(): Promise<void> {
	const vectors = [];
	for (const c of CASES) {
		const res = await evaluateScript({
			script: c.script,
			budget: { total: 1_000_000, spent: 0 },
			completedResults: {},
			knownCallIds: [],
			seenLogCount: 0,
		});
		if (res.status !== "need") {
			throw new Error(
				`vector "${c.description}" expected status 'need' but got '${res.status}' (${res.error?.message ?? ""})`,
			);
		}
		vectors.push({
			description: c.description,
			script: c.script,
			expectedTasks: res.tasks.map((t) => ({
				callId: t.callId,
				baseHash: t.baseHash,
				occurrence: t.occurrence,
				kind: t.kind,
				prompt: t.prompt,
				...(t.kind === "workflow"
					? { workflowRef: t.workflowRef, args: t.args }
					: { label: t.opts.label, schema: t.opts.schema }),
			})),
		});
	}

	const out = {
		$comment:
			"Generated by services/script-evaluator/scripts/generate-vectors.ts. Pins the FROZEN callId derivation (baseHash = sha256(prompt + NUL + canonicalJSON(semanticOpts)); callId = baseHash[:40] + '_' + occurrence). Regenerate with `pnpm gen:vectors` in services/script-evaluator. Consumed by the orchestrator pytest suite.",
		evaluatorVersion: EVALUATOR_VERSION,
		vectors,
	};

	const target = fileURLToPath(
		new URL(
			"../../shared/contracts/script-evaluator-callid-vectors.json",
			import.meta.url,
		),
	);
	mkdirSync(dirname(target), { recursive: true });
	writeFileSync(target, JSON.stringify(out, null, 2) + "\n", "utf8");
	console.log(`wrote ${vectors.length} vectors → ${target}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
